version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: marketmate
      POSTGRES_USER: marketmate_user
      POSTGRES_PASSWORD: marketmate_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketmate
      SPRING_DATASOURCE_USERNAME: marketmate_user
      SPRING_DATASOURCE_PASSWORD: marketmate_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
