version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: marketmate-postgres
    restart: always
    environment:
      POSTGRES_USER: marketmate
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marketmate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
