package com.marketmate.model;

import com.marketmate.entity.ChatMessage;

/**
 * Represents a response from the LLM provider.
 */
public class APIResponse {
    /** Unique identifier of the chat completion */
    private String id;
    /** Number of tokens in the prompt */
    private int promptTokens;
    /** Number of tokens in the generated completion */
    private int completionTokens;
    /** Timestamp (in seconds) when the chat completion was created */
    private long created;
    /** Chat completion message generated by the LLM. Role of the message is AI */
    private ChatMessage message;
    /**
     * Reason the model stopped generating tokens (e.g. STOP, LENGTH,
     * CONTENT_FILTER)
     */
    private String finishReason;

    public APIResponse() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getPromptTokens() {
        return promptTokens;
    }

    public void setPromptTokens(int promptTokens) {
        this.promptTokens = promptTokens;
    }

    public int getCompletionTokens() {
        return completionTokens;
    }

    public void setCompletionTokens(int completionTokens) {
        this.completionTokens = completionTokens;
    }

    public long getCreated() {
        return created;
    }

    public void setCreated(long created) {
        this.created = created;
    }

    public ChatMessage getMessage() {
        return message;
    }

    public void setMessage(ChatMessage message) {
        this.message = message;
    }

    public String getFinishReason() {
        return finishReason;
    }

    public void setFinishReason(String finishReason) {
        this.finishReason = finishReason;
    }
}
